import { expect, test } from '@playwright/test'

import { OFFICER, OPERATOR, auditSummaries, openCase, seedVisitConfirmed, signIn, signOut, status } from '../helpers.js'

/** Workflow 8 (US-060): the officer opens the checklist from the case, records findings, saves the draft,
 * and the case shows the summary. Submit (US-063) extends this scenario. */
test('checklist: open from the case, assess items, save the draft, see the summary', async ({ page }) => {
  const app = await seedVisitConfirmed()

  await signIn(page, OFFICER)
  await openCase(page, app.reference)
  await expect(page.getByRole('button', { name: 'Mark site visit done' })).toBeEnabled()
  await page.getByRole('link', { name: 'Open checklist' }).click()
  await expect(page.getByRole('heading', { name: 'Site visit checklist' })).toBeVisible()
  await expect(page.getByText('Draft, not submitted')).toBeVisible()
  const groups = page.getByRole('group', { name: 'Result' })
  await expect(groups).toHaveCount(17)
  await expect(page.getByText('0 of 17 assessed, 0 flagged').first()).toBeVisible()
  await expect(page.getByRole('button', { name: 'Mark visit done and submit' })).toBeDisabled()

  await groups.nth(0).getByRole('button', { name: 'Satisfactory', exact: true }).click()
  await groups.nth(1).getByRole('button', { name: 'Unsatisfactory', exact: true }).click()
  await expect(page.getByText('A comment is required for an unsatisfactory or flagged item.')).toBeVisible()
  await expect(page.getByText('1 comment missing')).toBeVisible()
  await page.getByLabel(/Comment/).fill('Floor slopes away from the trap; water pools by the wok station.')
  await page.getByLabel('Need further clarification').nth(1).check()
  await groups.nth(16).getByRole('button', { name: 'Not applicable' }).click()
  await expect(page.getByText('3 of 17 assessed, 1 flagged').first()).toBeVisible()
  await expect(page.getByText('Assess 14 more items to submit.')).toBeVisible()
  // a finding of the officer's own, under Other findings (US-092): titled, assessed, saved with its own key
  await page.getByRole('button', { name: 'Add a finding' }).click()
  await expect(page.getByText('Give the finding a title.')).toBeVisible()
  await page.getByRole('textbox', { name: /^Other finding/ }).fill('Loose floor tiles at the rear exit')
  await page.getByRole('group', { name: 'Result' }).nth(17).getByRole('button', { name: 'Satisfactory', exact: true }).click()
  await expect(page.getByText('4 of 18 assessed, 1 flagged').first()).toBeVisible()
  // pressing the selected result again clears it; autosave fires 1.5 s after the last touch (US-061)
  await groups.nth(16).getByRole('button', { name: 'Not applicable' }).click()
  await expect(groups.nth(16).getByRole('button', { name: 'Not applicable' })).toHaveAttribute('aria-pressed', 'false')
  await groups.nth(16).getByRole('button', { name: 'Not applicable' }).click()
  await expect(page.getByText('Saved just now')).toBeVisible({ timeout: 5000 })

  // the draft survives a reload and the case summarises it
  await page.reload()
  await expect(page.getByText('4 of 18 assessed, 1 flagged').first()).toBeVisible()
  await expect(page.getByRole('textbox', { name: /^Other finding/ })).toHaveValue('Loose floor tiles at the rear exit')
  await expect(groups.nth(1).getByRole('button', { name: 'Unsatisfactory', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByLabel(/Comment/)).toHaveValue('Floor slopes away from the trap; water pools by the wok station.')
  await page.getByRole('link', { name: 'Back to the case' }).click()
  await expect(status(page)).toHaveText('Site Visit Scheduled')
  await expect(page.locator('section:has(#checklist-title)')).toContainText('Visit 1: 4 of 18 assessed, 1 flagged')
  await expect(page.getByRole('link', { name: 'Continue checklist' })).toBeVisible()
  // no route straight to approval any more: the checklist is the way (US-063)
  await expect(page.getByRole('button', { name: 'Route to approval' })).toHaveCount(0)

  // ---- finish and submit with one flagged item ----
  await page.getByRole('link', { name: 'Continue checklist' }).click()
  await expect(page.getByRole('heading', { name: 'Site visit checklist' })).toBeVisible()
  for (let i = 2; i < 16; i += 1) await groups.nth(i).getByRole('button', { name: 'Satisfactory', exact: true }).click()
  await expect(page.getByText('Saved just now')).toBeVisible({ timeout: 5000 })
  await expect(page.getByText('Everything is assessed. Submit when you are ready.')).toBeVisible()
  await page.getByRole('button', { name: 'Mark visit done and submit' }).click()
  const dialog = page.locator('dialog[open]')
  await expect(dialog).toContainText('1 flagged item')
  await expect(dialog).toContainText('Floor trap in the food preparation area')
  await dialog.getByRole('button', { name: 'Submit' }).click()
  await expect(status(page)).toHaveText('Awaiting Post-Site Clarification')
  await expect(page.locator('section:has(#checklist-title)')).toContainText('Submitted')
  await expect(page.getByRole('link', { name: 'View checklist' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Route to approval' })).toBeDisabled()
  const trail = await auditSummaries(page)
  expect(trail).toContain('Status: Site Visit Scheduled → Site Visit Done')
  expect(trail.some((t) => t.startsWith('Checklist submitted'))).toBe(true)
  expect(trail).toContain('Status: Site Visit Done → Awaiting Post-Site Clarification')
  // the submitted checklist is read-only
  await page.getByRole('link', { name: 'View checklist' }).click()
  await expect(page.getByText('The findings are final.')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Save draft' })).toHaveCount(0)
  await signOut(page)

  // ---- the operator is told once, with the count, and sees no result ----
  await signIn(page, OPERATOR)
  await page.goto(app.url)
  await expect(status(page)).toHaveText('Pending Post-Site Clarification')
  await expect(page.getByText(/needs more information on 1 item/).first()).toBeVisible()
  await expect(page.locator('main')).not.toContainText('Unsatisfactory')
  await page.getByRole('button', { name: /Notifications/ }).click()
  await expect(page.getByRole('dialog', { name: 'Notifications' })).toContainText(`${app.reference}: Pending Post-Site Clarification`)
  await page.keyboard.press('Escape')
  // only the flagged item, the officer's note first (US-064)
  await page.getByRole('link', { name: 'Respond to clarification (1 item)' }).click()
  await expect(page.getByText('Round 1: 1 of 1 item needs your response')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Floor trap in the food preparation area' })).toBeVisible()
  await expect(page.getByText('Floor slopes away from the trap; water pools by the wok station.')).toBeVisible()
  await expect(page.getByText('Waiting for your response')).toBeVisible()
  await expect(page.locator('main')).not.toContainText('Layout matches the submitted floor plan')

  // ---- the operator answers, attaches a file, sends (US-065) ----
  await expect(page.getByRole('button', { name: 'Send responses' })).toBeDisabled()
  await page.getByLabel(/Your answer/).fill('Regraded on 23 Sep; water now runs to the trap. Photo attached.')
  await page.getByLabel(/Your answer/).blur()
  await expect(page.getByRole('button', { name: 'Choose a file' })).toBeVisible()
  await page.locator('input[type=file][multiple]').setInputFiles({
    name: 'floor-trap.txt',
    mimeType: 'text/plain',
    buffer: Buffer.from('Photo description: floor regraded, water runs to the trap.'),
  })
  await expect(page.getByRole('button', { name: 'floor-trap.txt' })).toBeVisible()
  await expect(page.getByText('1 of 3 files attached.')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Send responses' })).toBeEnabled()
  await page.getByRole('button', { name: 'Send responses' }).click()
  await page.locator('dialog[open]').getByRole('button', { name: 'Send responses' }).click()
  await expect(page.getByText('Round 1: every item is answered')).toBeVisible()
  await expect(page.getByText('Sent', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Send responses' })).toHaveCount(0)
  await page.getByRole('link', { name: 'Back to the application' }).click()
  await expect(status(page)).toHaveText('Post-Site Resubmitted')
  await expect(page.getByRole('heading', { name: 'Your answers were sent to the licensing office' })).toBeVisible()
  await signOut(page)

  // ---- the officer is told and the case is theirs again ----
  await signIn(page, OFFICER)
  await openCase(page, app.reference)
  await expect(status(page)).toHaveText('Post-Site Clarification Resubmitted')
  await page.getByRole('button', { name: /Notifications/ }).click()
  await expect(page.getByRole('dialog', { name: 'Notifications' })).toContainText('The operator answered the clarification request')
  await page.keyboard.press('Escape')

  // ---- round 2: the officer asks again, requests another round; the operator answers; clarified; approval (US-066) ----
  const rail = page.locator('section:has(#clarification-title)')
  await expect(rail).toContainText('Round 1, your turn')
  await expect(rail).toContainText('Regraded on 23 Sep; water now runs to the trap. Photo attached.')
  await expect(rail.getByRole('button', { name: /floor-trap.txt/ })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Route to approval' })).toBeDisabled()
  await rail.getByRole('button', { name: 'Still needs clarification' }).click()
  await rail.getByLabel(/What is still unclear/).fill('Please attach a photo of the drainage test.')
  await rail.getByRole('button', { name: 'Draft the question' }).click()
  await expect(rail).toContainText('Not sent yet')
  await expect(page.getByRole('button', { name: 'Request another round' })).toBeEnabled()
  await page.getByRole('button', { name: 'Request another round' }).click()
  await page.locator('dialog[open]').getByRole('button', { name: 'Request another round' }).click()
  await expect(status(page)).toHaveText('Awaiting Post-Site Resubmission')
  await expect(rail).toContainText('Round 2, waiting on operator')
  await signOut(page)

  await signIn(page, OPERATOR)
  await page.goto(app.url)
  await expect(status(page)).toHaveText('Pending Post-Site Resubmission')
  await page.getByRole('link', { name: 'Respond to clarification (1 item)' }).click()
  await expect(page.getByText('Round 2: 1 of 1 item needs your response')).toBeVisible()
  await expect(page.getByText('Please attach a photo of the drainage test.')).toBeVisible()
  await page.getByLabel(/Your answer/).fill('Drainage test done; water clears in 20 seconds.')
  await page.getByLabel(/Your answer/).blur()
  await expect(page.getByRole('button', { name: 'Send responses' })).toBeEnabled()
  await page.getByRole('button', { name: 'Send responses' }).click()
  await page.locator('dialog[open]').getByRole('button', { name: 'Send responses' }).click()
  await expect(page.getByText('Round 2: every item is answered')).toBeVisible()
  await page.getByRole('link', { name: 'Back to the application' }).click()
  await page.getByRole('link', { name: 'History' }).click()
  await expect(page.locator('section:has(#clar-history-title)')).toContainText('round 2')
  await expect(page.locator('section:has(#clar-history-title)')).toContainText('Drainage test done')
  await signOut(page)

  await signIn(page, OFFICER)
  await openCase(page, app.reference)
  await expect(rail).toContainText('Round 2, your turn')
  await expect(rail).toContainText('Drainage test done; water clears in 20 seconds.')
  await rail.getByRole('button', { name: 'Mark clarified' }).click()
  await expect(rail).toContainText('0 open · 0 answered · 1 clarified')
  await expect(page.getByRole('button', { name: 'Route to approval' })).toBeEnabled()
  await page.getByRole('button', { name: 'Route to approval' }).click()
  await page.locator('dialog[open]').getByRole('button', { name: 'Route to approval' }).click()
  await expect(status(page)).toHaveText('Route to Approval')
  const finalTrail = await auditSummaries(page)
  expect(finalTrail.some((t) => t.startsWith('Item floor_trap_graded still needs clarification'))).toBe(true)
  expect(finalTrail.some((t) => t.startsWith('Question on floor_trap_graded sent to the operator (round 2)'))).toBe(true)
  expect(finalTrail).toContain('Item floor_trap_graded marked clarified')
  expect(finalTrail).toContain('Status: Post-Site Clarification Resubmitted → Route to Approval')
})
